package constant;


import java.util.stream.Stream;

public interface Constanta {
    String BOT_TOKEN = "5628914728:AAFHuG3Sjghxob-d-5px0AmGivPtCEV80ao";
    String BOT_USERNAME = "https://t.me/springDemotelegramBot";
    String START = "/start";
    String PROFILE = "PROFILE⚙";
    String PRODUCTS = "PRODUCTS\uD83D\uDECD";
    String CATEGORIES = "CATEGORIES\uD83D\uDDC2";
    String FAVORITES = "FAVORITES❤";
    String ADMIN = "/admin";
    String ADMIN_ID = "1181112349";


    String BOLALAR_DUNYOSI = "BOLALAR DUNYOSI\uD83D\uDC76";
    String KOCHMAS_MULK = "KOCHMAS MULK\uD83C\uDFE0";
    String TRANSPORT = "TRANSPORT\uD83D\uDE99";
    String ISH = "ISH\uD83D\uDCBC";
    String UY_JIHOZLARI = "UY JIHOZLARI\uD83E\uDE91";
    String ELEKTRONIKA = "ELEKTRONIKA\uD83D\uDCF1";
    String BACK = "BACK";
    String ALL_CATEGORIES = "ALL CATEGORIES";
    String ALL_USERS = "ALL USERS";
    String ADD_CATEGORY = "ADD CATEGORY";
    String STATISTICS = "STATISTICS";


    String BOLALAR_KIYIMI = "BOLALAR KIYIMI";
    String BOLALAR_MEBELI = "BOLALAR MEBELI";
    String BOLALAR_MAHSULOTLARI = "BOLALAR MAHSULOTLARI";
    String BOLALAR_OZIQ_OVQATI = "BOLALAR OZIQ OVQATI";

    String KVARTIRALAR = "KVARTIRALAR";
    String UY_JOY = "UY JOY";
    String YER = "YER";
    String TIJORAT_BINOLARI = "TIJORAT BINOLARI";

    String YENGIL_AVTO = "YENGIL AVTOMOBILLAR";
    String YUK_AVTO = "YUK AVTOMOBILLARI";
    String MOTO_AKSESUARLARI = "MOTOTSIKL QISMLARI VA AKSESUARLARI";
    String AVTO_AKSESUARLARI = "AVTO EHTIYOT QISMLARI VA AKSESUARLARI";
    String BOSHQA_TRANSPORT = "BOSHQA TRANSPORT";

    String CHAKANA_SAVDO = "CHAKANA SAVDO / SOTIQ";
    String HUQUQ_BUGALTERIYA = "HUQUQ BUGALTERIYA";
    String TURIZM = "TURIZM";
    String IT = "IT / Telekom";
    String TRANSPORT_LOGISTIKA = "TRANSPORT_LOGISTIKA";
    String TALIM = "TA`LIM";
    String XAVFSIZLIK = "XAVFSIZLIK";
    String QURILISH = "QURILISH";
    String MARKETING = "MARKETING";

    String MEBEL = "MEBEL";
    String INSTRUMENTLAR = "INSTRUMENTLAR";
    String KANTSELARIYA_TOVARLARI = "KANTSELARIYA TOVARLARI";
    String INTERYER_BUYUMLAR = "INTERYER BUYUMLAR";
    String IDISH_OSHXONA_ANJOMLARI = "IDISH OSHXONA ANJOMLARI";
    String OZIQ_OVQAT_ICHIMLIKLAR = "OZIQ OVQAT ICHIMLIKLAR";
    String QURILISH_TAMIRLASH = "QURILISH VA TAMIRLASH UCHUN TOVARLAR";

    String TELEFONLAR = "TELEFONLAR";
    String AUDIO = "AUDIO";
    String IQLIM_USKUNALARI = "IQLIM USKUNALARI";
    String KOMPUTERLAR = "KOMPUTERLAR";
    String OYIN_KONSOLLARI = "O`YIN KONSOLLARI";
    String FOTO_VIDEO = "FOTO/VIDEO";
    String MAISHIY_TEXNIKA = "MAISHIY TEXNIKA";
    String AKSESUARLAR = "AKSESUARLAR";
    String TV = "TV";

}
